### ISSUE TITLE
New section: Types of experiments in bottom-up proteomics

### ISSUE THREAD

**Issue by dschust-r** [jessegmeyerlab/proteomics-tutorial#1]
I was wondering if we should include an additional section called something like **_Types of experiments in bottom-up proteomics_** where we could explain the different things bottom-up proteomics can be used for. I think this would be nice to add after the introduction (or maybe as part of the introduction?)?

Just a list of a few examples:

- Protein abundance changes
- Phosphoproteomics
- Glycoproteomics
- Structural techniques (XL-MS, HDX-MS, FPOP, protein-painting, LiP-MS, ...)
- Protein stability measurements (Thermal denaturation)
- PPIs: AP-MS, APEX, BioID
- ...

Adding something like this to the discussion would probably then also have an influence on what is discussed further on in the manuscript (for example in the data analysis and biological interpretation sections).

**Comment by jessegmeyerlab** [comment]
Thanks for your comment. Yes absolutely I agree. To add a section we would just need to change the numberings in the names of all the other sections as well so they appear in the correct order in the final version. I can do that later today or feel free to try submitting a pull request.
