### ISSUE TITLE
Biological interpretation figures are not showing

### ISSUE THREAD

**Issue by jessegmeyerlab** [jessegmeyerlab/proteomics-tutorial#64]
Hi @ger225 your biological interpretation figures are not showing and I don't see them in the images folder on the main branch so I think its just because it can't find them. Can you please make a pull request adding them to the images folder on main?

**Comment by ger225** [comment]
Hi @jessegmeyerlab, I made a pull request with the images. I don´t know if I did it correctly, but do not hesitate to ask whatever you need.

**Comment by jessegmeyerlab** [comment]
Nice it worked thank you!
