### ISSUE TITLE
Add author 

### ISSUE THREAD

**Issue by jessegmeyerlab** [jessegmeyerlab/proteomics-tutorial#72]
@norbertvolkmar please add your information to the metadata.yml file under the content folder so we can add you as author.

**Comment by jessegmeyerlab** [comment]
@norbertvolkmar do you want to be added as an author? If yes can you please either add an entry to the metadata.yml with your info or send me the following information and I'm happy to do it for you:

  - github: jessegmeyerlab
    name: Jesse G. Meyer
    initials: JGM
    orcid: 0000-0003-2753-3926
    twitter: j_my_sci
    email: jessegmeyer@gmail.com
    affiliations:
      - Department of Computational Biomedicine, Cedars Sinai Medical Center
    funders:
      - Grant R21 AG074234
      - Grant R35 GM142502

**Comment by norbertvolkmar** [comment]
Dear Jesse, 

I have added my info some time ago, but it seems to have disappeared or something went wrong with the pull request. Anyway, just in case, here is the info:

    github: norbertvolkmar
    name: Norbert Volkmar
    initials: NV
    orcid: 0000-0003-0766-5606
    twitter: NorbertVolkmar    
    email: norbertvolkmar22@gmail.com
    affiliations:
      - Department of Biology, Institute of Molecular Systems Biology, ETH Zurich, Zurich 8093, Switzerland
      - DISCO Pharmaceuticals, Zurich 8093, Switzerland

**Comment by jessegmeyerlab** [comment]
Merged, thank you for your contributions! Hoping to circulate the final version to everyone in early August
